// frontend/src/components/Wali/CekParaf.tsx
/**
 * ═══════════════════════════════════════════════════════
 * Wali Cek Paraf Component - Parent Verification Check
 * ═══════════════════════════════════════════════════════
 */

import React, { useState, useEffect } from 'react';
import { API_URL } from '../../config/env';

interface StudentVerification {
  id: number;
  name: string;
  username: string;
  kelas: string;
  day: number | null;
  has_data: boolean;
  parent_verified: number;
  parent_name?: string;
  parent_signature?: string;
  parent_verified_at?: string;
  pages: number;
  verification_status: 'verified' | 'pending' | 'no_data';
}

interface CekParafProps {
  user: any;
}

const CekParaf: React.FC<CekParafProps> = ({ user }) => {
  const [selectedDay, setSelectedDay] = useState(1);
  const [verifications, setVerifications] = useState<StudentVerification[]>([]);
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState({
    verified: 0,
    pending: 0,
    noData: 0,
  });

  useEffect(() => {
    loadVerifications(selectedDay);
  }, [selectedDay]);

  const loadVerifications = async (day: number) => {
    setLoading(true);
    try {
      const token = localStorage.getItem('rm_token');
      const response = await fetch(`${API_URL}/wali/verification-summary?day=${day}`, {
        headers: { 'Authorization': `Bearer ${token}` },
      });
      
      const result = await response.json();
      setVerifications(result.summary || []);
      
      // Calculate stats
      const verified = result.summary?.filter((s: any) => s.verification_status === 'verified').length || 0;
      const pending = result.summary?.filter((s: any) => s.verification_status === 'pending').length || 0;
      const noData = result.summary?.filter((s: any) => s.verification_status === 'no_data').length || 0;
      
      setStats({ verified, pending, noData });
    } catch (error) {
      console.error('Error loading verifications:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleReset = async (studentId: number, day: number, studentName: string) => {
    if (!confirm(`⚠️ Yakin ingin membatalkan verifikasi untuk:\n\n👤 Siswa: ${studentName}\n📅 Hari: ${day}\n\nSiswa akan dapat mengisi ulang kegiatan hari ini.`)) {
      return;
    }

    try {
      const token = localStorage.getItem('rm_token');
      const response = await fetch(`${API_URL}/wali/siswa/${studentId}/reset-verification`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({ day }),
      });

      const result = await response.json();

      if (response.ok) {
        alert('✅ ' + result.message);
        loadVerifications(selectedDay); // Reload list
      } else {
        alert('❌ ' + (result.error || 'Gagal mereset verifikasi'));
      }
    } catch (error) {
      alert('❌ Terjadi kesalahan');
    }
  };

  if (loading) {
    return (
      <div style={{ 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'center', 
        minHeight: '200px' 
      }}>
        <div style={{ color: 'var(--gold)', fontSize: '24px' }}>
          ⏳ Memuat...
        </div>
      </div>
    );
  }

  return (
    <div style={{ padding: '20px', maxWidth: '1000px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{
        background: 'linear-gradient(135deg, var(--emerald-dark), var(--emerald))',
        padding: '20px',
        borderRadius: '16px',
        marginBottom: '20px',
        color: 'var(--white)',
      }}>
        <h2 style={{ 
          fontFamily: "'Playfair Display', serif", 
          fontSize: '20px', 
          marginBottom: '4px' 
        }}>
          📝 Cek Paraf Orang Tua Per Hari
        </h2>
        <p style={{ fontSize: '13px', opacity: 0.9 }}>
          {user.name} - Kelas {user.kelas}
        </p>
      </div>

      {/* Day Selector */}
      <div style={{
        background: 'var(--cream)',
        borderRadius: '16px',
        padding: '18px',
        border: '1px solid rgba(201, 150, 60, 0.2)',
        marginBottom: '20px',
      }}>
        <label style={{
          fontSize: '12px',
          fontWeight: '700',
          color: 'var(--ink-soft)',
          marginBottom: '10px',
          display: 'block',
          textTransform: 'uppercase',
        }}>
          Pilih Hari:
        </label>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(10, 1fr)',
          gap: '6px',
        }}>
          {Array.from({ length: 30 }, (_, i) => i + 1).map(day => (
            <button
              key={day}
              onClick={() => setSelectedDay(day)}
              style={{
                aspectRatio: '1',
                border: '2px solid rgba(26, 92, 69, 0.2)',
                borderRadius: '10px',
                background: selectedDay === day ? 'var(--emerald)' : 'var(--cream)',
                color: selectedDay === day ? 'var(--white)' : 'var(--emerald-dark)',
                fontSize: '13px',
                fontWeight: '800',
                cursor: 'pointer',
                transition: 'all 0.18s',
                boxShadow: selectedDay === day ? '0 3px 10px rgba(26, 92, 69, 0.3)' : 'none',
              }}
            >
              {day}
            </button>
          ))}
        </div>
      </div>

      {/* Stats */}
      <div style={{
        display: 'flex',
        gap: '8px',
        marginBottom: '20px',
        flexWrap: 'wrap',
      }}>
        <div style={{
          padding: '4px 10px',
          borderRadius: '20px',
          fontSize: '11px',
          fontWeight: '700',
          background: 'rgba(26, 92, 69, 0.12)',
          color: 'var(--emerald)',
          border: '1px solid rgba(26, 92, 69, 0.3)',
          display: 'flex',
          alignItems: 'center',
          gap: '4px',
        }}>
          ✅ {stats.verified} Terverifikasi
        </div>
        <div style={{
          padding: '4px 10px',
          borderRadius: '20px',
          fontSize: '11px',
          fontWeight: '700',
          background: 'rgba(201, 150, 60, 0.12)',
          color: 'var(--gold)',
          border: '1px solid rgba(201, 150, 60, 0.3)',
          display: 'flex',
          alignItems: 'center',
          gap: '4px',
        }}>
          ⏳ {stats.pending} Pending
        </div>
        <div style={{
          padding: '4px 10px',
          borderRadius: '20px',
          fontSize: '11px',
          fontWeight: '700',
          background: '#f0f0f0',
          color: '#888',
          border: '1px solid #ccc',
          display: 'flex',
          alignItems: 'center',
          gap: '4px',
        }}>
          📝 {stats.noData} Belum Isi
        </div>
      </div>

      {/* Verification List */}
      <div style={{
        background: 'var(--cream)',
        borderRadius: '16px',
        padding: '18px',
        border: '1px solid rgba(201, 150, 60, 0.2)',
      }}>
        {verifications.length === 0 ? (
          <div style={{
            textAlign: 'center',
            padding: '30px 16px',
            color: 'var(--ink-soft)',
          }}>
            <div style={{ fontSize: '38px', marginBottom: '8px' }}>👆</div>
            <p>Pilih hari untuk melihat status paraf orang tua.</p>
          </div>
        ) : (
          <div>
            {verifications.map(student => {
              const statusConfig = {
                verified: { icon: '✅', color: 'var(--emerald)', bg: 'rgba(26, 92, 69, 0.15)', label: 'Terverifikasi' },
                pending: { icon: '⏳', color: 'var(--gold)', bg: 'rgba(201, 150, 60, 0.15)', label: 'Belum Paraf' },
                no_data: { icon: '📝', color: '#999', bg: '#f5f5f5', label: 'Belum Isi' },
              };
              const cfg = statusConfig[student.verification_status];

              return (
                <div
                  key={student.id}
                  style={{
                    display: 'flex',
                    alignItems: 'flex-start',
                    gap: '10px',
                    padding: '14px 0',
                    borderBottom: '1px dashed rgba(201, 150, 60, 0.15)',
                  }}
                >
                  <div style={{
                    width: '42px',
                    height: '42px',
                    borderRadius: '12px',
                    background: cfg.bg,
                    color: cfg.color,
                    fontSize: '16px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: '0',
                    fontWeight: '700',
                  }}>
                    {student.name[0]}
                  </div>
                  <div style={{ flex: '1', minWidth: '0' }}>
                    <div style={{
                      fontWeight: '700',
                      color: cfg.color,
                      marginBottom: '6px',
                      fontSize: '14px',
                    }}>
                      {cfg.icon} {student.name}
                    </div>
                    <div style={{
                      fontSize: '11px',
                      color: 'var(--ink-soft)',
                    }}>
                      {student.has_data ? (student.pages > 0 ? `${student.pages} halaman Qur'an` : 'Sudah mengisi kegiatan') : 'Belum mengisi kegiatan'}
                    </div>
                    
                    {/* Signature Thumbnail (if verified) */}
                    {student.parent_signature && (
                      <div style={{ marginTop: '8px' }}>
                        <div style={{ fontSize: '9px', color: 'var(--ink-soft)', marginBottom: '4px', fontWeight: '700' }}>
                          ✍️ Tanda Tangan
                        </div>
                        <img
                          src={student.parent_signature}
                          alt="TTD"
                          style={{
                            width: '80px',
                            height: '60px',
                            objectFit: 'contain',
                            background: '#fff',
                            borderRadius: '6px',
                            border: '2px solid var(--gold)',
                            cursor: 'pointer',
                            boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
                          }}
                          onClick={() => {
                            // Open in modal (TODO: Implement modal)
                            const w = window.open('', '_blank');
                            w?.document.write(`<img src="${student.parent_signature}" style="max-width:100%" />`);
                          }}
                        />
                      </div>
                    )}
                  </div>
                  <div style={{
                    textAlign: 'right',
                    flexShrink: '0',
                    minWidth: '140px',
                    marginLeft: '12px',
                  }}>
                    <span style={{
                      padding: '6px 10px',
                      borderRadius: '12px',
                      fontSize: '10px',
                      fontWeight: '700',
                      background: cfg.bg,
                      color: cfg.color,
                      border: '1px solid ' + cfg.color,
                      display: 'block',
                      marginBottom: '6px',
                    }}>
                      {cfg.label}
                    </span>
                    {student.parent_name && (
                      <div style={{ fontSize: '11px', color: 'var(--ink-soft)', fontWeight: '600' }}>
                        👤 {student.parent_name}
                      </div>
                    )}
                    {student.parent_verified_at && (
                      <div style={{ fontSize: '10px', color: '#999', marginTop: '3px' }}>
                        📅 {new Date(student.parent_verified_at).toLocaleDateString('id-ID', {
                          day: 'numeric',
                          month: 'short',
                          year: 'numeric',
                        })}
                      </div>
                    )}
                    
                    {/* Reset Button (only for verified) */}
                    {student.verification_status === 'verified' && student.day && (
                      <button
                        onClick={() => handleReset(student.id, student.day, student.name)}
                        style={{
                          marginTop: '8px',
                          padding: '4px 10px',
                          fontSize: '10px',
                          background: 'var(--red)',
                          color: '#fff',
                          border: 'none',
                          borderRadius: '6px',
                          fontWeight: '700',
                          cursor: 'pointer',
                        }}
                      >
                        🔄 Batalkan Verifikasi
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

export default CekParaf;

// amaliah/src/lib/components/Wali/CekParaf.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { apiGet, apiPost } from '$lib/utils/api';
	import { toastStore } from '$lib/stores/toast.store';
	import Skeleton from '$lib/components/Skeleton.svelte';

	interface User {
		id: number;
		name: string;
		username: string;
		role: string;
		kelas?: string;
	}

	interface VerificationSummary {
		id: number;
		name: string;
		username: string;
		kelas: string;
		day: number | null;
		has_data: boolean;
		parent_verified: number;
		parent_name: string | null;
		parent_signature: string | null;
		parent_verified_at: string | null;
		pages: number;
		verification_status: 'verified' | 'pending' | 'no_data';
	}

	interface Props {
		user: User;
	}

	let { user }: Props = $props();

	let selectedDay = $state(1);
	let summary = $state<VerificationSummary[]>([]);
	let loading = $state(true);
	let resetLoading = $state<Record<number, boolean>>({});

	onMount(() => {
		loadSummary();
	});

	$effect(() => {
		loadSummary();
	});

	async function loadSummary() {
		loading = true;
		try {
			const response = await apiGet<{ summary: VerificationSummary[] }>(
				`/api/wali/verification-summary?day=${selectedDay}`
			);

			if (response.data) {
				summary = response.data.summary;
			}
		} catch (error) {
			console.error('[CekParaf] Error:', error);
			toastStore.error('Gagal memuat data verifikasi');
		} finally {
			loading = false;
		}
	}

	function getStats() {
		const verified = summary.filter((s) => s.verification_status === 'verified').length;
		const pending = summary.filter((s) => s.verification_status === 'pending').length;
		const noData = summary.filter((s) => s.verification_status === 'no_data').length;
		return { verified, pending, noData, total: summary.length };
	}

	async function handleReset(siswaId: number, siswaName: string) {
		if (!confirm(`Reset verifikasi ${siswaName} untuk hari ke-${selectedDay}?`)) {
			return;
		}

		resetLoading[siswaId] = true;

		try {
			const response = await apiPost(`/api/wali/siswa/${siswaId}/reset-verification`, {
				day: selectedDay
			});

			if (response.error) {
				toastStore.error(response.error);
			} else {
				toastStore.success(response.message || 'Verifikasi berhasil direset');
				await loadSummary();
			}
		} catch (error) {
			console.error('[CekParaf] Reset error:', error);
			toastStore.error('Gagal mereset verifikasi');
		} finally {
			delete resetLoading[siswaId];
		}
	}

	function getStatusBadge(status: string) {
		if (status === 'verified')
			return '<span class="badge verified">✅ Terverifikasi</span>';
		if (status === 'pending')
			return '<span class="badge pending">⏳ Pending</span>';
		return '<span class="badge no-data">— Belum Isi</span>';
	}
</script>

<div class="cekparaf-container">
	<div class="header-section">
		<h2>📝 Cek Paraf Orang Tua</h2>
		<div class="day-selector">
			<label for="day">Hari ke-</label>
			<select id="day" bind:value={selectedDay}>
				{#each Array.from({ length: 30 }, (_, i) => i + 1) as day}
					<option value={day}>Hari {day}</option>
				{/each}
			</select>
		</div>
	</div>

	{#if loading}
		<div class="loading-state">
			<Skeleton width="100%" height="300px" />
		</div>
	{:else}
		<div class="content-section">
			<!-- Stats Badges -->
			<div class="stats-grid">
				<div class="stat-badge verified">
					<div class="stat-value">{getStats().verified}</div>
					<div class="stat-label">Terverifikasi</div>
				</div>
				<div class="stat-badge pending">
					<div class="stat-value">{getStats().pending}</div>
					<div class="stat-label">Pending</div>
				</div>
				<div class="stat-badge no-data">
					<div class="stat-value">{getStats().noData}</div>
					<div class="stat-label">Belum Isi</div>
				</div>
				<div class="stat-badge total">
					<div class="stat-value">{getStats().total}</div>
					<div class="stat-label">Total Siswa</div>
				</div>
			</div>

			<!-- Students List -->
			<div class="students-section">
				<h3>Daftar Siswa ({summary.length})</h3>
				{#if summary.length === 0}
					<div class="empty-state">
						<p>Belum ada data siswa</p>
					</div>
				{:else}
					<div class="students-list">
						{#each summary as siswa}
							<div class="student-card {siswa.verification_status}">
								<div class="student-info">
									<div class="student-name">{siswa.name}</div>
									<div class="student-username">@{siswa.username}</div>
									{#if siswa.parent_verified === 1}
										<div class="parent-info">
											<span class="parent-name">👤 {siswa.parent_name}</span>
											{#if siswa.parent_verified_at}
												<span class="verified-at">
													{new Date(siswa.parent_verified_at).toLocaleDateString('id-ID')}
												</span>
											{/if}
										</div>
									{/if}
								</div>
								<div class="student-status">
									{#if siswa.verification_status === 'verified'}
										<span class="badge verified">✅ Terverifikasi</span>
									{:else if siswa.verification_status === 'pending'}
										<span class="badge pending">⏳ Pending</span>
									{:else}
										<span class="badge no-data">— Belum Isi</span>
									{/if}
								</div>
								{#if siswa.verification_status !== 'no_data'}
									<button
										class="btn-reset"
										onclick={() => handleReset(siswa.id, siswa.name)}
										disabled={resetLoading[siswa.id]}
									>
										🔄 Reset
									</button>
								{/if}
							</div>
						{/each}
					</div>
				{/if}
			</div>
		</div>
	{/if}
</div>

<style>
	.cekparaf-container {
		max-width: 48rem;
		margin: 0 auto;
		padding: 1rem;
	}

	.header-section {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 1rem;
	}

	.header-section h2 {
		font-size: 1.25rem;
		font-weight: 700;
		color: #c9963c;
		margin: 0;
	}

	.day-selector {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.day-selector label {
		font-size: 0.875rem;
		color: rgba(255, 255, 255, 0.8);
	}

	.day-selector select {
		padding: 0.5rem 1rem;
		border: 1px solid rgba(255, 255, 255, 0.2);
		border-radius: 0.5rem;
		background: rgba(255, 255, 255, 0.05);
		color: white;
		font-size: 0.875rem;
	}

	.loading-state {
		margin-top: 1rem;
	}

	.content-section {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.stats-grid {
		display: grid;
		grid-template-columns: repeat(4, 1fr);
		gap: 0.75rem;
	}

	.stat-badge {
		background: rgba(255, 255, 255, 0.05);
		border: 1px solid rgba(255, 255, 255, 0.1);
		border-radius: 0.5rem;
		padding: 0.75rem;
		text-align: center;
	}

	.stat-badge.verified {
		border-color: rgba(16, 185, 129, 0.3);
		background: rgba(16, 185, 129, 0.05);
	}

	.stat-badge.pending {
		border-color: rgba(234, 179, 8, 0.3);
		background: rgba(234, 179, 8, 0.05);
	}

	.stat-badge.no-data {
		border-color: rgba(107, 114, 128, 0.3);
		background: rgba(107, 114, 128, 0.05);
	}

	.stat-badge.total {
		border-color: rgba(201, 150, 60, 0.3);
		background: rgba(201, 150, 60, 0.05);
	}

	.stat-value {
		font-size: 1.25rem;
		font-weight: 700;
		color: #c9963c;
	}

	.stat-label {
		font-size: 0.625rem;
		color: rgba(255, 255, 255, 0.7);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		margin-top: 0.25rem;
	}

	.students-section h3 {
		font-size: 1rem;
		font-weight: 700;
		color: rgba(255, 255, 255, 0.9);
		margin: 0;
	}

	.empty-state {
		text-align: center;
		padding: 2rem;
		background: rgba(255, 255, 255, 0.05);
		border-radius: 0.75rem;
	}

	.empty-state p {
		color: rgba(255, 255, 255, 0.6);
	}

	.students-list {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.student-card {
		background: rgba(255, 255, 255, 0.05);
		border: 1px solid rgba(255, 255, 255, 0.1);
		border-radius: 0.5rem;
		padding: 1rem;
		display: flex;
		justify-content: space-between;
		align-items: center;
		gap: 1rem;
	}

	.student-card.verified {
		border-color: rgba(16, 185, 129, 0.3);
		background: rgba(16, 185, 129, 0.05);
	}

	.student-card.pending {
		border-color: rgba(234, 179, 8, 0.3);
		background: rgba(234, 179, 8, 0.05);
	}

	.student-info {
		flex: 1;
	}

	.student-name {
		font-weight: 700;
		color: rgba(255, 255, 255, 0.9);
		margin-bottom: 0.25rem;
	}

	.student-username {
		font-size: 0.875rem;
		color: rgba(255, 255, 255, 0.6);
		margin-bottom: 0.25rem;
	}

	.parent-info {
		display: flex;
		gap: 1rem;
		font-size: 0.75rem;
		color: rgba(255, 255, 255, 0.6);
	}

	.student-status {
		flex-shrink: 0;
	}

	.badge {
		display: inline-block;
		padding: 0.375rem 0.75rem;
		border-radius: 0.375rem;
		font-size: 0.75rem;
		font-weight: 600;
		white-space: nowrap;
	}

	.badge.verified {
		background: rgba(16, 185, 129, 0.2);
		color: #10b981;
	}

	.badge.pending {
		background: rgba(234, 179, 8, 0.2);
		color: #eab308;
	}

	.badge.no-data {
		background: rgba(107, 114, 128, 0.2);
		color: #6b7280;
	}

	.btn-reset {
		padding: 0.5rem 1rem;
		background: rgba(239, 68, 68, 0.2);
		color: #ef4444;
		border: 1px solid rgba(239, 68, 68, 0.3);
		border-radius: 0.375rem;
		font-size: 0.75rem;
		font-weight: 600;
		cursor: pointer;
		transition: transform 0.2s;
		flex-shrink: 0;
	}

	.btn-reset:hover:not(:disabled) {
		transform: translateY(-2px);
	}

	.btn-reset:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	@media (max-width: 640px) {
		.stats-grid {
			grid-template-columns: repeat(2, 1fr);
		}

		.student-card {
			flex-direction: column;
			align-items: flex-start;
		}

		.student-status {
			margin-top: 0.5rem;
		}

		.btn-reset {
			margin-top: 0.5rem;
		}
	}
</style>
