// frontend/src/components/Wali/Verifikasi.tsx
/**
 * ═══════════════════════════════════════════════════════
 * Wali Verifikasi Component - Student Approval
 * ═══════════════════════════════════════════════════════
 */

import React, { useState, useEffect } from 'react';
import { API_URL } from '../../config/env';

interface Student {
  id: number;
  name: string;
  username: string;
  kelas: string;
  verified: number;
}

interface VerifikasiProps {
  user: any;
}

const Verifikasi: React.FC<VerifikasiProps> = ({ user }) => {
  const [pendingStudents, setPendingStudents] = useState<Student[]>([]);
  const [allStudents, setAllStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<number | null>(null);

  useEffect(() => {
    loadStudents();
  }, []);

  const loadStudents = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('rm_token');
      
      // Load pending students
      const pendingRes = await fetch(`${API_URL}/wali/siswa/pending`, {
        headers: { 'Authorization': `Bearer ${token}` },
      });
      const pendingData = await pendingRes.json();
      setPendingStudents(pendingData.siswa || []);

      // Load all students
      const allRes = await fetch(`${API_URL}/wali/siswa`, {
        headers: { 'Authorization': `Bearer ${token}` },
      });
      const allData = await allRes.json();
      setAllStudents(allData.siswa || []);
    } catch (error) {
      console.error('Error loading students:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleVerify = async (studentId: number, action: 'approve' | 'reject') => {
    setActionLoading(studentId);
    try {
      const token = localStorage.getItem('rm_token');
      const reason = action === 'reject' ? prompt('Alasan penolakan (opsional):') : undefined;
      
      const response = await fetch(`${API_URL}/wali/siswa/${studentId}/verify`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({ action, reason }),
      });

      const result = await response.json();

      if (response.ok) {
        alert(action === 'approve' ? '✅ Verifikasi sukses' : '❌ Siswa ditolak');
        loadStudents(); // Reload list
      } else {
        alert('❌ ' + (result.error || 'Gagal memproses'));
      }
    } catch (error) {
      alert('❌ Terjadi kesalahan');
    } finally {
      setActionLoading(null);
    }
  };

  if (loading) {
    return (
      <div style={{ 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'center', 
        minHeight: '200px' 
      }}>
        <div style={{ color: 'var(--gold)', fontSize: '24px' }}>
          ⏳ Memuat...
        </div>
      </div>
    );
  }

  return (
    <div style={{ padding: '20px', maxWidth: '800px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{
        background: 'linear-gradient(135deg, var(--emerald-dark), var(--emerald))',
        padding: '20px',
        borderRadius: '16px',
        marginBottom: '20px',
        color: 'var(--white)',
      }}>
        <h2 style={{ 
          fontFamily: "'Playfair Display', serif", 
          fontSize: '20px', 
          marginBottom: '4px' 
        }}>
          ✅ Verifikasi Siswa
        </h2>
        <p style={{ fontSize: '13px', opacity: 0.9 }}>
          {user.name} - Kelas {user.kelas}
        </p>
      </div>

      {/* Pending Students */}
      <div style={{ marginBottom: '20px' }}>
        <div style={{
          background: 'var(--cream)',
          borderRadius: '16px',
          padding: '18px',
          border: '1px solid rgba(201, 150, 60, 0.2)',
        }}>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: '12px',
          }}>
            <h3 style={{
              fontFamily: "'Playfair Display', serif",
              fontSize: '15px',
              color: 'var(--emerald-dark)',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
            }}>
              ⏳ Siswa Pending Verifikasi
              <span style={{
                padding: '2px 10px',
                borderRadius: '20px',
                fontSize: '11px',
                fontWeight: '700',
                background: 'rgba(201, 150, 60, 0.15)',
                color: 'var(--gold)',
                border: '1px solid rgba(201, 150, 60, 0.4)',
              }}>
                {pendingStudents.length}
              </span>
            </h3>
          </div>

          {pendingStudents.length === 0 ? (
            <div style={{
              textAlign: 'center',
              padding: '30px 16px',
              color: 'var(--ink-soft)',
            }}>
              <div style={{ fontSize: '38px', marginBottom: '8px' }}>🎉</div>
              <p>Tidak ada siswa pending.</p>
            </div>
          ) : (
            <div>
              {pendingStudents.map(student => (
                <div
                  key={student.id}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '10px',
                    padding: '10px 0',
                    borderBottom: '1px dashed rgba(201, 150, 60, 0.18)',
                  }}
                >
                  <div style={{
                    width: '38px',
                    height: '38px',
                    borderRadius: '12px',
                    background: 'var(--emerald)',
                    color: 'var(--gold-light)',
                    fontSize: '16px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    flexShrink: '0',
                    fontWeight: '700',
                  }}>
                    {student.name[0]}
                  </div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{
                      fontSize: '13px',
                      fontWeight: '700',
                      color: 'var(--ink)',
                      whiteSpace: 'nowrap',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                    }}>
                      {student.name}
                    </div>
                    <div style={{
                      fontSize: '11px',
                      color: 'var(--ink-soft)',
                    }}>
                      @{student.username} {student.kelas ? `· Kelas ${student.kelas}` : ''}
                    </div>
                  </div>
                  <div style={{ display: 'flex', gap: '6px', flexShrink: '0' }}>
                    <button
                      onClick={() => handleVerify(student.id, 'approve')}
                      disabled={actionLoading === student.id}
                      style={{
                        padding: '5px 10px',
                        borderRadius: '8px',
                        border: '1px solid rgba(26, 92, 69, 0.3)',
                        background: 'rgba(26, 92, 69, 0.12)',
                        color: 'var(--emerald)',
                        fontSize: '11px',
                        fontWeight: '700',
                        cursor: actionLoading === student.id ? 'not-allowed' : 'pointer',
                        opacity: actionLoading === student.id ? 0.6 : 1,
                        transition: 'all 0.18s',
                      }}
                    >
                      {actionLoading === student.id ? '⏳' : '✓'} Setujui
                    </button>
                    <button
                      onClick={() => handleVerify(student.id, 'reject')}
                      disabled={actionLoading === student.id}
                      style={{
                        padding: '5px 10px',
                        borderRadius: '8px',
                        border: '1px solid rgba(192, 57, 43, 0.3)',
                        background: 'var(--red-soft)',
                        color: 'var(--red)',
                        fontSize: '11px',
                        fontWeight: '700',
                        cursor: actionLoading === student.id ? 'not-allowed' : 'pointer',
                        opacity: actionLoading === student.id ? 0.6 : 1,
                        transition: 'all 0.18s',
                      }}
                    >
                      {actionLoading === student.id ? '⏳' : '✗'} Tolak
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* All Students */}
      <div>
        <div style={{
          background: 'var(--cream)',
          borderRadius: '16px',
          padding: '18px',
          border: '1px solid rgba(201, 150, 60, 0.2)',
        }}>
          <h3 style={{
            fontFamily: "'Playfair Display', serif",
            fontSize: '15px',
            color: 'var(--emerald-dark)',
            marginBottom: '12px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
          }}>
            ✅ Semua Siswa Kelas {user.kelas}
          </h3>

          {allStudents.length === 0 ? (
            <div style={{
              textAlign: 'center',
              padding: '30px 16px',
              color: 'var(--ink-soft)',
            }}>
              <div style={{ fontSize: '38px', marginBottom: '8px' }}>👥</div>
              <p>Belum ada siswa terdaftar di kelas ini.</p>
            </div>
          ) : (
            <div>
              {allStudents.map(student => {
                const status = student.verified === 1 ? 'approved' : student.verified === 2 ? 'rejected' : 'pending';
                const statusLabel = { approved: '✅ Terverifikasi', rejected: '❌ Ditolak', pending: '⏳ Pending' }[status];
                
                return (
                  <div
                    key={student.id}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '10px',
                      padding: '10px 0',
                      borderBottom: '1px dashed rgba(201, 150, 60, 0.18)',
                    }}
                  >
                    <div style={{
                      width: '38px',
                      height: '38px',
                      borderRadius: '12px',
                      background: status === 'approved' ? 'rgba(26, 92, 69, 0.12)' : 
                                 status === 'rejected' ? 'var(--red-soft)' : 'rgba(201, 150, 60, 0.15)',
                      color: status === 'approved' ? 'var(--emerald)' : 
                             status === 'rejected' ? 'var(--red)' : 'var(--gold)',
                      fontSize: '16px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      flexShrink: '0',
                      fontWeight: '700',
                    }}>
                      {student.name[0]}
                    </div>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{
                        fontSize: '13px',
                        fontWeight: '700',
                        color: 'var(--ink)',
                        whiteSpace: 'nowrap',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                      }}>
                        {student.name}
                      </div>
                      <div style={{
                        fontSize: '11px',
                        color: 'var(--ink-soft)',
                      }}>
                        @{student.username} {student.kelas ? `· Kelas ${student.kelas}` : ''}
                      </div>
                    </div>
                    <span style={{
                      padding: '4px 10px',
                      borderRadius: '20px',
                      fontSize: '10px',
                      fontWeight: '700',
                      background: status === 'approved' ? 'rgba(26, 92, 69, 0.1)' : 
                                 status === 'rejected' ? 'var(--red-soft)' : 'rgba(201, 150, 60, 0.15)',
                      color: status === 'approved' ? 'var(--emerald)' : 
                             status === 'rejected' ? 'var(--red)' : 'var(--gold)',
                      border: '1px solid ' + (status === 'approved' ? 'rgba(26, 92, 69, 0.3)' : 
                                            status === 'rejected' ? 'rgba(192, 57, 43, 0.3)' : 'rgba(201, 150, 60, 0.4)'),
                    }}>
                        {statusLabel}
                    </span>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Verifikasi;

// amaliah/src/lib/components/Wali/Verifikasi.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { apiGet, apiPut } from '$lib/utils/api';
	import { toastStore } from '$lib/stores/toast.store';
	import Skeleton from '$lib/components/Skeleton.svelte';

	interface User {
		id: number;
		name: string;
		username: string;
		role: string;
		kelas?: string;
	}

	interface Siswa {
		id: number;
		name: string;
		username: string;
		kelas: string;
		verified: number;
	}

	interface Props {
		user: User;
	}

	let { user }: Props = $props();

	let siswaList = $state<Siswa[]>([]);
	let pendingList = $state<Siswa[]>([]);
	let loading = $state(true);
	let actionLoading = $state<Record<number, boolean>>({});

	onMount(async () => {
		await Promise.all([loadSiswa(), loadPending()]);
		loading = false;
	});

	async function loadSiswa() {
		const response = await apiGet<{ siswa: Siswa[] }>('/api/wali/siswa');
		if (response.data) {
			siswaList = response.data.siswa;
		}
	}

	async function loadPending() {
		const response = await apiGet<{ siswa: Siswa[] }>('/api/wali/siswa?pending=true');
		if (response.data) {
			pendingList = response.data.siswa;
		}
	}

	async function handleVerify(siswaId: number, action: 'approve' | 'reject', reason?: string) {
		actionLoading[siswaId] = true;

		try {
			const response = await apiPut(`/api/wali/siswa/${siswaId}/verify`, { action, reason });

			if (response.error) {
				toastStore.error(response.error);
			} else {
				toastStore.success(response.message || 'Verifikasi berhasil');
				await loadPending();
				await loadSiswa();
			}
		} catch (error) {
			console.error('[Verifikasi] Error:', error);
			toastStore.error('Gagal memverifikasi siswa');
		} finally {
			delete actionLoading[siswaId];
		}
	}

	function getStatusBadge(verified: number) {
		if (verified === 1) return '<span class="badge approved">✅ Disetujui</span>';
		if (verified === 2) return '<span class="badge rejected">❌ Ditolak</span>';
		return '<span class="badge pending">⏳ Pending</span>';
	}
</script>

<div class="verifikasi-container">
	<div class="header-section">
		<h2>✅ Verifikasi Siswa</h2>
	</div>

	{#if loading}
		<div class="loading-state">
			<Skeleton width="100%" height="200px" />
		</div>
	{:else}
		<div class="content-section">
			<!-- Pending Students -->
			<div class="section">
				<h3>⏳ Menunggu Verifikasi ({pendingList.length})</h3>
				{#if pendingList.length === 0}
					<div class="empty-state">
						<p>Tidak ada siswa menunggu verifikasi</p>
					</div>
				{:else}
					<div class="students-list">
						{#each pendingList as siswa}
							<div class="student-card">
								<div class="student-info">
									<div class="student-name">{siswa.name}</div>
									<div class="student-username">@{siswa.username}</div>
								</div>
								<div class="student-actions">
									<button
										class="btn-approve"
										onclick={() => handleVerify(siswa.id, 'approve')}
										disabled={actionLoading[siswa.id]}
									>
										✅ Terima
									</button>
									<button
										class="btn-reject"
										onclick={() => handleVerify(siswa.id, 'reject', 'Tidak memenuhi syarat')}
										disabled={actionLoading[siswa.id]}
									>
										❌ Tolak
									</button>
								</div>
							</div>
						{/each}
					</div>
				{/if}
			</div>

			<!-- All Students -->
			<div class="section">
				<h3>👥 Semua Siswa ({siswaList.length})</h3>
				{#if siswaList.length === 0}
					<div class="empty-state">
						<p>Belum ada siswa di kelas Anda</p>
					</div>
				{:else}
					<div class="students-list">
						{#each siswaList as siswa}
							<div class="student-card">
								<div class="student-info">
									<div class="student-name">{siswa.name}</div>
									<div class="student-username">@{siswa.username}</div>
								</div>
								<div class="student-status">
									{#if siswa.verified === 1}
										<span class="badge approved">✅ Disetujui</span>
									{:else if siswa.verified === 2}
										<span class="badge rejected">❌ Ditolak</span>
									{:else}
										<span class="badge pending">⏳ Pending</span>
									{/if}
								</div>
							</div>
						{/each}
					</div>
				{/if}
			</div>
		</div>
	{/if}
</div>

<style>
	.verifikasi-container {
		max-width: 48rem;
		margin: 0 auto;
		padding: 1rem;
	}

	.header-section h2 {
		font-size: 1.25rem;
		font-weight: 700;
		color: #c9963c;
		margin: 0 0 1rem 0;
	}

	.loading-state {
		margin-top: 1rem;
	}

	.content-section {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.section h3 {
		font-size: 1rem;
		font-weight: 700;
		color: rgba(255, 255, 255, 0.9);
		margin: 0 0 1rem 0;
	}

	.empty-state {
		text-align: center;
		padding: 2rem;
		background: rgba(255, 255, 255, 0.05);
		border-radius: 0.75rem;
	}

	.empty-state p {
		color: rgba(255, 255, 255, 0.6);
	}

	.students-list {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.student-card {
		background: rgba(255, 255, 255, 0.05);
		border: 1px solid rgba(255, 255, 255, 0.1);
		border-radius: 0.5rem;
		padding: 1rem;
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.student-info {
		flex: 1;
	}

	.student-name {
		font-weight: 700;
		color: rgba(255, 255, 255, 0.9);
		margin-bottom: 0.25rem;
	}

	.student-username {
		font-size: 0.875rem;
		color: rgba(255, 255, 255, 0.6);
	}

	.student-actions {
		display: flex;
		gap: 0.5rem;
	}

	.btn-approve,
	.btn-reject {
		padding: 0.5rem 1rem;
		border: none;
		border-radius: 0.375rem;
		font-weight: 600;
		font-size: 0.875rem;
		cursor: pointer;
		transition: transform 0.2s;
	}

	.btn-approve {
		background: rgba(16, 185, 129, 0.2);
		color: #10b981;
		border: 1px solid rgba(16, 185, 129, 0.3);
	}

	.btn-reject {
		background: rgba(239, 68, 68, 0.2);
		color: #ef4444;
		border: 1px solid rgba(239, 68, 68, 0.3);
	}

	.btn-approve:hover:not(:disabled),
	.btn-reject:hover:not(:disabled) {
		transform: translateY(-2px);
	}

	.btn-approve:disabled,
	.btn-reject:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.student-status {
		flex-shrink: 0;
		margin-left: 1rem;
	}

	.badge {
		display: inline-block;
		padding: 0.375rem 0.75rem;
		border-radius: 0.375rem;
		font-size: 0.75rem;
		font-weight: 600;
	}

	.badge.approved {
		background: rgba(16, 185, 129, 0.2);
		color: #10b981;
	}

	.badge.rejected {
		background: rgba(239, 68, 68, 0.2);
		color: #ef4444;
	}

	.badge.pending {
		background: rgba(234, 179, 8, 0.2);
		color: #eab308;
	}
</style>
