// frontend/src/components/Auth/Login.tsx
/**
 * ═══════════════════════════════════════════════════════
 * Login Component
 * ═══════════════════════════════════════════════════════
 */

import React, { useState } from 'react';
import { API_URL } from '../../config/env';

interface User {
  id: number;
  name: string;
  username: string;
  role: 'admin' | 'wali_kelas' | 'siswa';
  kelas?: string;
  verified: number;
}

interface LoginProps {
  onLogin: (user: User, token: string) => void;
  onRegister: () => void;
}

const Login: React.FC<LoginProps> = ({ onLogin, onRegister }) => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const response = await fetch(`${API_URL}/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Login failed');
      }

      onLogin(data.user, data.token);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px',
    }}>
      <div style={{
        background: 'var(--cream)',
        borderRadius: '24px',
        padding: '32px 28px',
        width: '100%',
        maxWidth: '400px',
        boxShadow: '0 8px 40px rgba(0,0,0,0.3)',
        border: '1px solid rgba(201, 150, 60, 0.25)',
      }}>
        {/* Brand */}
        <div style={{ textAlign: 'center', marginBottom: '28px' }} role="banner">
          <div style={{ 
            fontFamily: "'Scheherazade New', serif", 
            fontSize: '28px', 
            color: 'var(--emerald)',
            marginBottom: '4px'
          }} aria-label="Bismillah">
            بسم الله الرحمن الرحيم
          </div>
          <h1 style={{ 
            fontFamily: "'Playfair Display', serif", 
            fontSize: '20px', 
            color: 'var(--emerald-dark)',
            fontWeight: '700'
          }}>
            📖 Buku Amaliah Ramadhan
          </h1>
          <p style={{ fontSize: '12px', color: 'var(--ink-soft)', marginTop: '2px' }}>
            Catatan ibadah harian selama Ramadhan
          </p>
          <p style={{ fontSize: '11px', color: 'var(--ink-soft)', marginTop: '6px', fontWeight: '700' }}>
            MTs Negeri 2 Kolaka Utara
          </p>
          <p style={{ fontSize: '11px', color: 'var(--ink-soft)', marginTop: '2px' }}>
            Dibuat oleh hasbi1028
          </p>
        </div>

        {/* Tabs */}
        <div style={{
          display: 'flex',
          background: 'var(--parchment)',
          borderRadius: '12px',
          padding: '4px',
          marginBottom: '24px',
          gap: '4px',
        }}>
          <button style={{
            flex: 1,
            padding: '8px',
            border: 'none',
            background: 'var(--emerald)',
            color: 'var(--white)',
            borderRadius: '9px',
            fontWeight: '700',
            fontSize: '13px',
            cursor: 'pointer',
          }}>
            Masuk
          </button>
          <button 
            onClick={onRegister}
            style={{
              flex: 1,
              padding: '8px',
              border: 'none',
              background: 'transparent',
              color: 'var(--ink-soft)',
              borderRadius: '9px',
              fontWeight: '700',
              fontSize: '13px',
              cursor: 'pointer',
            }}
          >
            Daftar
          </button>
        </div>

        {/* Error */}
        {error && (
          <div 
            role="alert" 
            aria-live="assertive"
            style={{
              background: 'var(--red-soft)',
              border: '1px solid rgba(192, 57, 43, 0.3)',
              color: 'var(--red)',
              borderRadius: '10px',
              padding: '10px 14px',
              fontSize: '13px',
              fontWeight: '600',
              marginBottom: '14px',
            }}
          >
            ❌ {error}
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleSubmit} aria-label="Login form">
          <div style={{ marginBottom: '14px' }}>
            <label 
              htmlFor="username"
              style={{
                display: 'block',
                fontSize: '12px',
                fontWeight: '700',
                color: 'var(--ink-soft)',
                marginBottom: '5px',
                textTransform: 'uppercase',
                letterSpacing: '0.5px',
              }}
            >
              Username
            </label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="Masukkan username"
              required
              autoComplete="username"
              aria-required="true"
              style={{
                width: '100%',
                padding: '10px 14px',
                border: '1.5px solid rgba(201, 150, 60, 0.3)',
                borderRadius: '10px',
                background: 'var(--white)',
                fontSize: '14px',
                color: 'var(--ink)',
                outline: 'none',
              }}
            />
          </div>

          <div style={{ marginBottom: '14px' }}>
            <label 
              htmlFor="password"
              style={{
                display: 'block',
                fontSize: '12px',
                fontWeight: '700',
                color: 'var(--ink-soft)',
                marginBottom: '5px',
                textTransform: 'uppercase',
                letterSpacing: '0.5px',
              }}
            >
              Password
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Masukkan password"
              required
              autoComplete="current-password"
              aria-required="true"
              style={{
                width: '100%',
                padding: '10px 14px',
                border: '1.5px solid rgba(201, 150, 60, 0.3)',
                borderRadius: '10px',
                background: 'var(--white)',
                fontSize: '14px',
                color: 'var(--ink)',
                outline: 'none',
              }}
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            aria-busy={loading}
            style={{
              display: 'block',
              width: '100%',
              padding: '12px',
              background: 'linear-gradient(135deg, var(--gold), var(--gold-light))',
              color: 'var(--emerald-dark)',
              border: 'none',
              borderRadius: '12px',
              fontSize: '15px',
              fontWeight: '800',
              cursor: loading ? 'not-allowed' : 'pointer',
              opacity: loading ? 0.6 : 1,
              marginTop: '4px',
            }}
          >
            {loading ? '⏳ Masuk...' : 'Masuk'}
          </button>
        </form>

        {/* Default credentials hint */}
        <div style={{
          marginTop: '20px',
          padding: '12px',
          background: 'rgba(26, 92, 69, 0.08)',
          border: '1px solid rgba(26, 92, 69, 0.2)',
          borderRadius: '10px',
          fontSize: '11px',
          color: 'var(--emerald-dark)',
        }}>
          <strong>Default Login:</strong><br/>
          Admin: admin / admin123<br/>
          Siswa: siswa7A / password123<br/>
          Wali: wali7A / password123
        </div>
      </div>
    </div>
  );
};

export default Login;

// amaliah/src/lib/components/Auth/Login.svelte
<script lang="ts">
	import { authStore } from '$lib/stores/auth.store';
	import { toastStore } from '$lib/stores/toast.store';
	import { apiPost } from '$lib/utils/api';
	import Skeleton from '$lib/components/Skeleton.svelte';

	interface User {
		id: number;
		name: string;
		username: string;
		role: 'admin' | 'wali_kelas' | 'siswa';
		kelas?: string;
		verified: number;
	}

	let username = $state('');
	let password = $state('');
	let loading = $state(false);
	let showPassword = $state(false);
	let loginError = $state<string | null>(null);

	function handleSubmit(e: Event) {
		e.preventDefault();
		loginError = null;

		if (!username.trim() || !password.trim()) {
			toastStore.error('Username dan password wajib diisi');
			return;
		}

		loading = true;

		apiPost<{ token: string; user: User; message: string }>('/api/auth/login', {
			username: username.trim(),
			password
		})
			.then((response) => {
				if (response.error || !response.data) {
					toastStore.error(response.error || 'Login gagal');
					loginError = response.error || 'Login gagal';
					return;
				}

				const { token, user } = response.data;
				authStore.login(user, token);
				toastStore.success(response.data.message || 'Login berhasil');
			})
			.catch((err) => {
				console.error('[Login] Error:', err);
				toastStore.error('Terjadi kesalahan. Silakan coba lagi.');
				loginError = 'Gagal terhubung ke server';
			})
			.finally(() => {
				loading = false;
			});
	}
</script>

<div class="login-container">
	<div class="login-card">
		<div class="login-header">
			<div class="logo">📖</div>
			<h1 class="title">Buku Amaliah Ramadhan</h1>
			<p class="subtitle">MTS Negeri 2 Kolaka Utara</p>
		</div>

		<form class="login-form" onsubmit={handleSubmit}>
			{#if loginError}
				<div class="error-message">
					⚠️ {loginError}
				</div>
			{/if}

			<div class="form-group">
				<label for="username">Username</label>
				<input
					id="username"
					type="text"
					bind:value={username}
					placeholder="Masukkan username"
					disabled={loading}
					autocomplete="username"
				/>
			</div>

			<div class="form-group">
				<label for="password">Password</label>
				<div class="password-input">
					<input
						id="password"
						type={showPassword ? 'text' : 'password'}
						bind:value={password}
						placeholder="Masukkan password"
						disabled={loading}
						autocomplete="current-password"
					/>
					<button
						type="button"
						class="toggle-password"
						onclick={() => (showPassword = !showPassword)}
						tabindex="-1"
					>
						{showPassword ? '🙈' : '👁️'}
					</button>
				</div>
			</div>

			<button type="submit" class="btn-login" disabled={loading}>
				{#if loading}
					<Skeleton width="80px" height="20px" />
				{:else}
					Masuk
				{/if}
			</button>
		</form>

		<div class="login-footer">
			<p>Belum punya akun?</p>
			<a href="/register" class="btn-register">Daftar</a>
		</div>
	</div>
</div>

<style>
	.login-container {
		display: flex;
		align-items: center;
		justify-content: center;
		min-height: 100vh;
		background: linear-gradient(160deg, #0f3d2e 0%, #1a5c45 100%);
		padding: 1rem;
	}

	.login-card {
		background: rgba(255, 255, 255, 0.05);
		backdrop-filter: blur(10px);
		border: 1px solid rgba(255, 255, 255, 0.1);
		border-radius: 1rem;
		padding: 2rem;
		width: 100%;
		max-width: 26rem;
		box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
	}

	.login-header {
		text-align: center;
		margin-bottom: 2rem;
	}

	.logo {
		font-size: 3rem;
		margin-bottom: 0.5rem;
	}

	.title {
		font-family: 'Playfair Display', serif;
		font-size: 1.5rem;
		font-weight: 700;
		color: #c9963c;
		margin-bottom: 0.25rem;
	}

	.subtitle {
		font-size: 0.875rem;
		color: rgba(255, 255, 255, 0.7);
	}

	.login-form {
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
	}

	.error-message {
		background: rgba(239, 68, 68, 0.1);
		border: 1px solid rgba(239, 68, 68, 0.3);
		color: #ef4444;
		padding: 0.75rem 1rem;
		border-radius: 0.5rem;
		font-size: 0.875rem;
		font-weight: 600;
		margin-bottom: 1rem;
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.form-group label {
		font-size: 0.875rem;
		font-weight: 600;
		color: rgba(255, 255, 255, 0.9);
	}

	.form-group input {
		padding: 0.75rem 1rem;
		border: 1px solid rgba(255, 255, 255, 0.2);
		border-radius: 0.5rem;
		background: rgba(255, 255, 255, 0.05);
		color: white;
		font-size: 1rem;
		transition: border-color 0.2s;
	}

	.form-group input::placeholder {
		color: rgba(255, 255, 255, 0.4);
	}

	.form-group input:focus {
		outline: none;
		border-color: #c9963c;
	}

	.password-input {
		position: relative;
		display: flex;
		align-items: center;
	}

	.password-input input {
		flex: 1;
		padding-right: 3rem;
	}

	.toggle-password {
		position: absolute;
		right: 0.75rem;
		background: none;
		border: none;
		font-size: 1.25rem;
		cursor: pointer;
		opacity: 0.7;
		transition: opacity 0.2s;
	}

	.toggle-password:hover {
		opacity: 1;
	}

	.btn-login {
		background: linear-gradient(135deg, #c9963c 0%, #f0c14b 100%);
		color: #0f3d2e;
		border: none;
		border-radius: 0.5rem;
		padding: 0.875rem 1.5rem;
		font-size: 1rem;
		font-weight: 700;
		cursor: pointer;
		transition: transform 0.2s, box-shadow 0.2s;
	}

	.btn-login:hover:not(:disabled) {
		transform: translateY(-2px);
		box-shadow: 0 10px 15px -3px rgba(201, 150, 60, 0.3);
	}

	.btn-login:disabled {
		opacity: 0.7;
		cursor: not-allowed;
	}

	.login-footer {
		margin-top: 1.5rem;
		text-align: center;
		color: rgba(255, 255, 255, 0.7);
		font-size: 0.875rem;
	}

	.btn-register {
		display: inline-block;
		margin-top: 0.5rem;
		color: #c9963c;
		font-weight: 600;
		text-decoration: none;
		transition: color 0.2s;
	}

	.btn-register:hover {
		color: #f0c14b;
	}
</style>
