// frontend/src/components/Auth/Register.tsx
/**
 * ═══════════════════════════════════════════════════════
 * Register Component
 * ═══════════════════════════════════════════════════════
 */

import React, { useState } from 'react';
import { API_URL } from '../../config/env';

interface RegisterProps {
  onBackToLogin: () => void;
}

const Register: React.FC<RegisterProps> = ({ onBackToLogin }) => {
  const [formData, setFormData] = useState({
    name: '',
    username: '',
    password: '',
    role: 'siswa' as 'siswa' | 'wali_kelas',
    kelas: '',
  });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setLoading(true);

    try {
      const response = await fetch(`${API_URL}/auth/register`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Registration failed');
      }

      setSuccess('✅ ' + data.message);
      setFormData({
        name: '',
        username: '',
        password: '',
        role: 'siswa',
        kelas: '',
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Registration failed');
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px',
    }}>
      <div style={{
        background: 'var(--cream)',
        borderRadius: '24px',
        padding: '32px 28px',
        width: '100%',
        maxWidth: '400px',
        boxShadow: '0 8px 40px rgba(0,0,0,0.3)',
        border: '1px solid rgba(201, 150, 60, 0.25)',
      }}>
        {/* Brand */}
        <div style={{ textAlign: 'center', marginBottom: '28px' }}>
          <div style={{ 
            fontFamily: "'Scheherazade New', serif", 
            fontSize: '28px', 
            color: 'var(--emerald)',
            marginBottom: '4px'
          }}>
            بسم الله الرحمن الرحيم
          </div>
          <h1 style={{ 
            fontFamily: "'Playfair Display', serif", 
            fontSize: '20px', 
            color: 'var(--emerald-dark)',
            fontWeight: '700'
          }}>
            📖 Daftar Akun Baru
          </h1>
          <p style={{ fontSize: '12px', color: 'var(--ink-soft)', marginTop: '2px' }}>
            Untuk siswa dan wali kelas
          </p>
        </div>

        {/* Tabs */}
        <div style={{
          display: 'flex',
          background: 'var(--parchment)',
          borderRadius: '12px',
          padding: '4px',
          marginBottom: '24px',
          gap: '4px',
        }}>
          <button 
            onClick={onBackToLogin}
            style={{
              flex: 1,
              padding: '8px',
              border: 'none',
              background: 'transparent',
              color: 'var(--ink-soft)',
              borderRadius: '9px',
              fontWeight: '700',
              fontSize: '13px',
              cursor: 'pointer',
            }}
          >
            Masuk
          </button>
          <button style={{
            flex: 1,
            padding: '8px',
            border: 'none',
            background: 'var(--emerald)',
            color: 'var(--white)',
            borderRadius: '9px',
            fontWeight: '700',
            fontSize: '13px',
            cursor: 'pointer',
          }}>
            Daftar
          </button>
        </div>

        {/* Messages */}
        {error && (
          <div style={{
            background: 'var(--red-soft)',
            border: '1px solid rgba(192, 57, 43, 0.3)',
            color: 'var(--red)',
            borderRadius: '10px',
            padding: '10px 14px',
            fontSize: '13px',
            fontWeight: '600',
            marginBottom: '14px',
          }}>
            ❌ {error}
          </div>
        )}

        {success && (
          <div style={{
            background: 'rgba(26, 92, 69, 0.08)',
            border: '1px solid rgba(26, 92, 69, 0.3)',
            color: 'var(--emerald-dark)',
            borderRadius: '10px',
            padding: '10px 14px',
            fontSize: '13px',
            fontWeight: '600',
            marginBottom: '14px',
          }}>
            {success}
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleSubmit}>
          <div style={{ marginBottom: '14px' }}>
            <label style={{
              display: 'block',
              fontSize: '12px',
              fontWeight: '700',
              color: 'var(--ink-soft)',
              marginBottom: '5px',
              textTransform: 'uppercase',
            }}>
              Nama Lengkap
            </label>
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              placeholder="Nama sesuai data sekolah"
              required
              style={{
                width: '100%',
                padding: '10px 14px',
                border: '1.5px solid rgba(201, 150, 60, 0.3)',
                borderRadius: '10px',
                fontSize: '14px',
              }}
            />
          </div>

          <div style={{ marginBottom: '14px' }}>
            <label style={{
              display: 'block',
              fontSize: '12px',
              fontWeight: '700',
              color: 'var(--ink-soft)',
              marginBottom: '5px',
              textTransform: 'uppercase',
            }}>
              Username
            </label>
            <input
              type="text"
              name="username"
              value={formData.username}
              onChange={handleChange}
              placeholder="Buat username unik"
              required
              style={{
                width: '100%',
                padding: '10px 14px',
                border: '1.5px solid rgba(201, 150, 60, 0.3)',
                borderRadius: '10px',
                fontSize: '14px',
              }}
            />
          </div>

          <div style={{ marginBottom: '14px' }}>
            <label style={{
              display: 'block',
              fontSize: '12px',
              fontWeight: '700',
              color: 'var(--ink-soft)',
              marginBottom: '5px',
              textTransform: 'uppercase',
            }}>
              Password
            </label>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder="Min. 6 karakter"
              required
              minLength={6}
              style={{
                width: '100%',
                padding: '10px 14px',
                border: '1.5px solid rgba(201, 150, 60, 0.3)',
                borderRadius: '10px',
                fontSize: '14px',
              }}
            />
          </div>

          <div style={{ marginBottom: '14px' }}>
            <label style={{
              display: 'block',
              fontSize: '12px',
              fontWeight: '700',
              color: 'var(--ink-soft)',
              marginBottom: '5px',
              textTransform: 'uppercase',
            }}>
              Daftar sebagai
            </label>
            <select
              name="role"
              value={formData.role}
              onChange={handleChange}
              required
              style={{
                width: '100%',
                padding: '10px 14px',
                border: '1.5px solid rgba(201, 150, 60, 0.3)',
                borderRadius: '10px',
                fontSize: '14px',
              }}
            >
              <option value="">-- Pilih role --</option>
              <option value="wali_kelas">Wali Kelas</option>
              <option value="siswa">Siswa</option>
            </select>
          </div>

          {(formData.role === 'wali_kelas' || formData.role === 'siswa') && (
            <div style={{ marginBottom: '14px' }}>
              <label style={{
                display: 'block',
                fontSize: '12px',
                fontWeight: '700',
                color: 'var(--ink-soft)',
                marginBottom: '5px',
                textTransform: 'uppercase',
              }}>
                Kelas
              </label>
              <input
                type="text"
                name="kelas"
                value={formData.kelas}
                onChange={handleChange}
                placeholder="Contoh: 7A, 8B, 9C"
                required
                style={{
                  width: '100%',
                  padding: '10px 14px',
                  border: '1.5px solid rgba(201, 150, 60, 0.3)',
                  borderRadius: '10px',
                  fontSize: '14px',
                }}
              />
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            style={{
              display: 'block',
              width: '100%',
              padding: '12px',
              background: 'linear-gradient(135deg, var(--emerald), var(--emerald-light))',
              color: 'var(--white)',
              border: 'none',
              borderRadius: '12px',
              fontSize: '15px',
              fontWeight: '800',
              cursor: loading ? 'not-allowed' : 'pointer',
              opacity: loading ? 0.6 : 1,
              marginTop: '4px',
            }}
          >
            {loading ? '⏳ Mendaftar...' : 'Daftar Sekarang'}
          </button>
        </form>
      </div>
    </div>
  );
};

export default Register;

// amaliah/src/lib/components/Auth/Register.svelte
<script lang="ts">
	import { toastStore } from '$lib/stores/toast.store';
	import { apiPost, apiGet } from '$lib/utils/api';
	import Skeleton from '$lib/components/Skeleton.svelte';

	interface ClassOption {
		id: number;
		name: string;
	}

	let name = $state('');
	let username = $state('');
	let password = $state('');
	let confirmPassword = $state('');
	let role = $state<'siswa' | 'wali_kelas'>('siswa');
	let selectedClass = $state('');
	let classes = $state<ClassOption[]>([]);
	let loading = $state(false);
	let showPassword = $state(false);
	let showConfirmPassword = $state(false);

	// Load classes on mount
	$effect(() => {
		apiGet<{ classes: ClassOption[] }>('/api/auth/classes')
			.then((response) => {
				if (response.data) {
					classes = response.data.classes;
				}
			})
			.catch(console.error);
	});

	function handleSubmit() {
		// Validation
		if (!name.trim() || !username.trim() || !password || !confirmPassword) {
			toastStore.error('Semua field wajib diisi');
			return;
		}

		if (password !== confirmPassword) {
			toastStore.error('Password tidak cocok');
			return;
		}

		if (password.length < 6) {
			toastStore.error('Password minimal 6 karakter');
			return;
		}

		if (!selectedClass) {
			toastStore.error('Kelas wajib dipilih');
			return;
		}

		loading = true;

		apiPost('/api/auth/register', {
			name: name.trim(),
			username: username.trim(),
			password,
			role,
			kelas: selectedClass
		})
			.then((response) => {
				if (response.error) {
					toastStore.error(response.error);
					return;
				}

				toastStore.success(response.message || 'Registrasi berhasil. Silakan tunggu verifikasi.');
				// Reset form
				name = '';
				username = '';
				password = '';
				confirmPassword = '';
				selectedClass = '';
			})
			.catch(() => {
				toastStore.error('Terjadi kesalahan. Silakan coba lagi.');
			})
			.finally(() => {
				loading = false;
			});
	}
</script>

<div class="register-container">
	<div class="register-card">
		<div class="register-header">
			<div class="logo">📖</div>
			<h1 class="title">Daftar Akun Baru</h1>
			<p class="subtitle">Buku Amaliah Ramadhan</p>
		</div>

		<form class="register-form" onsubmit={(e) => (e.preventDefault(), handleSubmit())}>
			<div class="form-group">
				<label for="name">Nama Lengkap</label>
				<input
					id="name"
					type="text"
					bind:value={name}
					placeholder="Masukkan nama lengkap"
					disabled={loading}
					autocomplete="name"
				/>
			</div>

			<div class="form-group">
				<label for="username">Username</label>
				<input
					id="username"
					type="text"
					bind:value={username}
					placeholder="Masukkan username"
					disabled={loading}
					autocomplete="username"
				/>
			</div>

			<div class="form-group">
				<label for="role">Daftar Sebagai</label>
				<select
					id="role"
					bind:value={role}
					disabled={loading}
				>
					<option value="siswa">Siswa</option>
					<option value="wali_kelas">Wali Kelas</option>
				</select>
			</div>

			<div class="form-group">
				<label for="kelas">Kelas</label>
				<select
					id="kelas"
					bind:value={selectedClass}
					disabled={loading}
				>
					<option value="">Pilih Kelas</option>
					{#each classes as cls}
						<option value={cls.name}>{cls.name}</option>
					{/each}
				</select>
			</div>

			<div class="form-group">
				<label for="password">Password</label>
				<div class="password-input">
					<input
						id="password"
						type={showPassword ? 'text' : 'password'}
						bind:value={password}
						placeholder="Minimal 6 karakter"
						disabled={loading}
						autocomplete="new-password"
					/>
					<button
						type="button"
						class="toggle-password"
						onclick={() => (showPassword = !showPassword)}
						tabindex="-1"
					>
						{showPassword ? '🙈' : '👁️'}
					</button>
				</div>
			</div>

			<div class="form-group">
				<label for="confirmPassword">Konfirmasi Password</label>
				<div class="password-input">
					<input
						id="confirmPassword"
						type={showConfirmPassword ? 'text' : 'password'}
						bind:value={confirmPassword}
						placeholder="Ulangi password"
						disabled={loading}
						autocomplete="new-password"
					/>
					<button
						type="button"
						class="toggle-password"
						onclick={() => (showConfirmPassword = !showConfirmPassword)}
						tabindex="-1"
					>
						{showConfirmPassword ? '🙈' : '👁️'}
					</button>
				</div>
			</div>

			<div class="form-actions">
				<button type="submit" class="btn-register" disabled={loading}>
					{#if loading}
						<Skeleton width="100px" height="20px" />
					{:else}
						Daftar
					{/if}
				</button>
			</div>
		</form>

		<div class="register-footer">
			<p>Sudah punya akun?</p>
			<a href="/login" class="btn-login">Masuk</a>
		</div>
	</div>
</div>

<style>
	.register-container {
		display: flex;
		align-items: center;
		justify-content: center;
		min-height: 100vh;
		background: linear-gradient(160deg, #0f3d2e 0%, #1a5c45 100%);
		padding: 1rem;
	}

	.register-card {
		background: rgba(255, 255, 255, 0.05);
		backdrop-filter: blur(10px);
		border: 1px solid rgba(255, 255, 255, 0.1);
		border-radius: 1rem;
		padding: 2rem;
		width: 100%;
		max-width: 28rem;
		max-height: 90vh;
		overflow-y: auto;
		box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
	}

	.register-header {
		text-align: center;
		margin-bottom: 1.5rem;
	}

	.logo {
		font-size: 2.5rem;
		margin-bottom: 0.5rem;
	}

	.title {
		font-family: 'Playfair Display', serif;
		font-size: 1.25rem;
		font-weight: 700;
		color: #c9963c;
		margin-bottom: 0.25rem;
	}

	.subtitle {
		font-size: 0.75rem;
		color: rgba(255, 255, 255, 0.7);
	}

	.register-form {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.form-group label {
		font-size: 0.875rem;
		font-weight: 600;
		color: rgba(255, 255, 255, 0.9);
	}

	.form-group input,
	.form-group select {
		padding: 0.75rem 1rem;
		border: 1px solid rgba(255, 255, 255, 0.2);
		border-radius: 0.5rem;
		background: rgba(255, 255, 255, 0.05);
		color: white;
		font-size: 0.875rem;
		transition: border-color 0.2s;
	}

	.form-group select option {
		background: #0f3d2e;
		color: white;
	}

	.form-group input::placeholder {
		color: rgba(255, 255, 255, 0.4);
	}

	.form-group input:focus,
	.form-group select:focus {
		outline: none;
		border-color: #c9963c;
	}

	.password-input {
		position: relative;
		display: flex;
		align-items: center;
	}

	.password-input input {
		flex: 1;
		padding-right: 3rem;
	}

	.toggle-password {
		position: absolute;
		right: 0.75rem;
		background: none;
		border: none;
		font-size: 1.25rem;
		cursor: pointer;
		opacity: 0.7;
		transition: opacity 0.2s;
	}

	.toggle-password:hover {
		opacity: 1;
	}

	.form-actions {
		margin-top: 0.5rem;
	}

	.btn-register {
		width: 100%;
		background: linear-gradient(135deg, #c9963c 0%, #f0c14b 100%);
		color: #0f3d2e;
		border: none;
		border-radius: 0.5rem;
		padding: 0.875rem;
		font-size: 1rem;
		font-weight: 700;
		cursor: pointer;
		transition: transform 0.2s, box-shadow 0.2s;
	}

	.btn-register:hover:not(:disabled) {
		transform: translateY(-2px);
		box-shadow: 0 10px 15px -3px rgba(201, 150, 60, 0.3);
	}

	.btn-register:disabled {
		opacity: 0.7;
		cursor: not-allowed;
	}

	.register-footer {
		margin-top: 1.5rem;
		text-align: center;
		color: rgba(255, 255, 255, 0.7);
		font-size: 0.875rem;
	}

	.btn-login {
		display: inline-block;
		margin-top: 0.5rem;
		color: #c9963c;
		font-weight: 600;
		text-decoration: none;
		transition: color 0.2s;
	}

	.btn-login:hover {
		color: #f0c14b;
	}
</style>
